export const countriesWithCodes = [
    { displayLabel: 'Afghanistan', code: 'AF' },
    { displayLabel: 'Albania', code: 'AL' },
    { displayLabel: 'Algeria', code: 'DZ' },
    { displayLabel: 'Andorra', code: 'AD' },
    { displayLabel: 'Angola', code: 'AO' },
    { displayLabel: 'Antigua and Barbuda', code: 'AG' },
    { displayLabel: 'Argentina', code: 'AR' },
    { displayLabel: 'Armenia', code: 'AM' },
    { displayLabel: 'Australia', code: 'AU' },
    { displayLabel: 'Austria', code: 'AT' },
    { displayLabel: 'Azerbaijan', code: 'AZ' },
    { displayLabel: 'Bahamas', code: 'BS' },
    { displayLabel: 'Bahrain', code: 'BH' },
    { displayLabel: 'Bangladesh', code: 'BD' },
    { displayLabel: 'Barbados', code: 'BB' },
    { displayLabel: 'Belarus', code: 'BY' },
    { displayLabel: 'Belgium', code: 'BE' },
    { displayLabel: 'Belize', code: 'BZ' },
    { displayLabel: 'Benin', code: 'BJ' },
    { displayLabel: 'Bhutan', code: 'BT' },
    { displayLabel: 'Bolivia', code: 'BO' },
    { displayLabel: 'Bosnia and Herzegovina', code: 'BA' },
    { displayLabel: 'Botswana', code: 'BW' },
    { displayLabel: 'Brazil', code: 'BR' },
    { displayLabel: 'Brunei', code: 'BN' },
    { displayLabel: 'Bulgaria', code: 'BG' },
    { displayLabel: 'Burkina Faso', code: 'BF' },
    { displayLabel: 'Burundi', code: 'BI' },
    { displayLabel: 'Cabo Verde', code: 'CV' },
    { displayLabel: 'Cambodia', code: 'KH' },
    { displayLabel: 'Cameroon', code: 'CM' },
    { displayLabel: 'Canada', code: 'CA' },
    { displayLabel: 'Central African Republic', code: 'CF' },
    { displayLabel: 'Chad', code: 'TD' },
    { displayLabel: 'Chile', code: 'CL' },
    { displayLabel: 'China', code: 'CN' },
    { displayLabel: 'Colombia', code: 'CO' },
    { displayLabel: 'Comoros', code: 'KM' },
    { displayLabel: 'Costa Rica', code: 'CR' },
    { displayLabel: 'Croatia', code: 'HR' },
    { displayLabel: 'Cuba', code: 'CU' },
    { displayLabel: 'Cyprus', code: 'CY' },
    { displayLabel: 'Czech Republic', code: 'CZ' },
    { displayLabel: 'Democratic Republic of the Congo', code: 'CD' },
    { displayLabel: 'Denmark', code: 'DK' },
    { displayLabel: 'Djibouti', code: 'DJ' },
    { displayLabel: 'Dominica', code: 'DM' },
    { displayLabel: 'Dominican Republic', code: 'DO' },
    { displayLabel: 'Ecuador', code: 'EC' },
    { displayLabel: 'Egypt', code: 'EG' },
    { displayLabel: 'El Salvador', code: 'SV' },
    { displayLabel: 'Equatorial Guinea', code: 'GQ' },
    { displayLabel: 'Eritrea', code: 'ER' },
    { displayLabel: 'Estonia', code: 'EE' },
    { displayLabel: 'Eswatini', code: 'SZ' },
    { displayLabel: 'Ethiopia', code: 'ET' },
    { displayLabel: 'Fiji', code: 'FJ' },
    { displayLabel: 'Finland', code: 'FI' },
    { displayLabel: 'France', code: 'FR' },
    { displayLabel: 'Gabon', code: 'GA' },
    { displayLabel: 'Gambia', code: 'GM' },
    { displayLabel: 'Georgia', code: 'GE' },
    { displayLabel: 'Germany', code: 'DE' },
    { displayLabel: 'Ghana', code: 'GH' },
    { displayLabel: 'Greece', code: 'GR' },
    { displayLabel: 'Grenada', code: 'GD' },
    { displayLabel: 'Guatemala', code: 'GT' },
    { displayLabel: 'Guinea', code: 'GN' },
    { displayLabel: 'Guinea-Bissau', code: 'GW' },
    { displayLabel: 'Guyana', code: 'GY' },
    { displayLabel: 'Haiti', code: 'HT' },
    { displayLabel: 'Honduras', code: 'HN' },
    { displayLabel: 'Hungary', code: 'HU' },
    { displayLabel: 'Iceland', code: 'IS' },
    { displayLabel: 'India', code: 'IN' },
    { displayLabel: 'Indonesia', code: 'ID' },
    { displayLabel: 'Iran', code: 'IR' },
    { displayLabel: 'Iraq', code: 'IQ' },
    { displayLabel: 'Ireland', code: 'IE' },
    { displayLabel: 'Israel', code: 'IL' },
    { displayLabel: 'Italy', code: 'IT' },
    { displayLabel: 'Ivory Coast', code: 'CI' },
    { displayLabel: 'Jamaica', code: 'JM' },
    { displayLabel: 'Japan', code: 'JP' },
    { displayLabel: 'Jordan', code: 'JO' },
    { displayLabel: 'Kazakhstan', code: 'KZ' },
    { displayLabel: 'Kenya', code: 'KE' },
    { displayLabel: 'Kiribati', code: 'KI' },
    { displayLabel: 'Korea, North', code: 'KP' },
    { displayLabel: 'Korea, South', code: 'KR' },
    { displayLabel: 'Kuwait', code: 'KW' },
    { displayLabel: 'Kyrgyzstan', code: 'KG' },
    { displayLabel: 'Laos', code: 'LA' },
    { displayLabel: 'Latvia', code: 'LV' },
    { displayLabel: 'Lebanon', code: 'LB' },
    { displayLabel: 'Lesotho', code: 'LS' },
    { displayLabel: 'Liberia', code: 'LR' },
    { displayLabel: 'Libya', code: 'LY' },
    { displayLabel: 'Liechtenstein', code: 'LI' },
    { displayLabel: 'Lithuania', code: 'LT' },
    { displayLabel: 'Luxembourg', code: 'LU' },
    { displayLabel: 'Madagascar', code: 'MG' },
    { displayLabel: 'Malawi', code: 'MW' },
    { displayLabel: 'Malaysia', code: 'MY' },
    { displayLabel: 'Maldives', code: 'MV' },
    { displayLabel: 'Mali', code: 'ML' },
    { displayLabel: 'Malta', code: 'MT' },
    { displayLabel: 'Marshall Islands', code: 'MH' },
    { displayLabel: 'Mauritania', code: 'MR' },
    { displayLabel: 'Mauritius', code: 'MU' },
    { displayLabel: 'Mexico', code: 'MX' },
    { displayLabel: 'Micronesia', code: 'FM' },
    { displayLabel: 'Moldova', code: 'MD' },
    { displayLabel: 'Monaco', code: 'MC' },
    { displayLabel: 'Mongolia', code: 'MN' },
    { displayLabel: 'Montenegro', code: 'ME' },
    { displayLabel: 'Morocco', code: 'MA' },
    { displayLabel: 'Mozambique', code: 'MZ' },
    { displayLabel: 'Myanmar', code: 'MM' },
    { displayLabel: 'Namibia', code: 'NA' },
    { displayLabel: 'Nauru', code: 'NR' },
    { displayLabel: 'Nepal', code: 'NP' },
    { displayLabel: 'Netherlands', code: 'NL' },
    { displayLabel: 'New Zealand', code: 'NZ' },
    { displayLabel: 'Nicaragua', code: 'NI' },
    { displayLabel: 'Niger', code: 'NE' },
    { displayLabel: 'Nigeria', code: 'NG' },
    { displayLabel: 'North Macedonia', code: 'MK' },
    { displayLabel: 'Norway', code: 'NO' },
    { displayLabel: 'Oman', code: 'OM' },
    { displayLabel: 'Pakistan', code: 'PK' },
    { displayLabel: 'Palau', code: 'PW' },
    { displayLabel: 'Panama', code: 'PA' },
    { displayLabel: 'Papua New Guinea', code: 'PG' },
    { displayLabel: 'Paraguay', code: 'PY' },
    { displayLabel: 'Peru', code: 'PE' },
    { displayLabel: 'Philippines', code: 'PH' },
    { displayLabel: 'Poland', code: 'PL' },
    { displayLabel: 'Portugal', code: 'PT' },
    { displayLabel: 'Qatar', code: 'QA' },
    { displayLabel: 'Romania', code: 'RO' },
    { displayLabel: 'Russia', code: 'RU' },
    { displayLabel: 'Rwanda', code: 'RW' },
    { displayLabel: 'Saint Kitts and Nevis', code: 'KN' },
    { displayLabel: 'Saint Lucia', code: 'LC' },
    { displayLabel: 'Saint Vincent and the Grenadines', code: 'VC' },
    { displayLabel: 'Samoa', code: 'WS' },
    { displayLabel: 'San Marino', code: 'SM' },
    { displayLabel: 'Sao Tome and Principe', code: 'ST' },
    { displayLabel: 'Saudi Arabia', code: 'SA' },
    { displayLabel: 'Senegal', code: 'SN' },
    { displayLabel: 'Serbia', code: 'RS' },
    { displayLabel: 'Seychelles', code: 'SC' },
    { displayLabel: 'Sierra Leone', code: 'SL' },
    { displayLabel: 'Singapore', code: 'SG' },
    { displayLabel: 'Slovakia', code: 'SK' },
    { displayLabel: 'Slovenia', code: 'SI' },
    { displayLabel: 'Solomon Islands', code: 'SB' },
    { displayLabel: 'Somalia', code: 'SO' },
    { displayLabel: 'South Africa', code: 'ZA' },
    { displayLabel: 'South Sudan', code: 'SS' },
    { displayLabel: 'Spain', code: 'ES' },
    { displayLabel: 'Sri Lanka', code: 'LK' },
    { displayLabel: 'Sudan', code: 'SD' },
    { displayLabel: 'Suriname', code: 'SR' },
    { displayLabel: 'Sweden', code: 'SE' },
    { displayLabel: 'Switzerland', code: 'CH' },
    { displayLabel: 'Syria', code: 'SY' },
    { displayLabel: 'Taiwan', code: 'TW' },
    { displayLabel: 'Tajikistan', code: 'TJ' },
    { displayLabel: 'Tanzania', code: 'TZ' },
    { displayLabel: 'Thailand', code: 'TH' },
    { displayLabel: 'Timor-Leste', code: 'TL' },
    { displayLabel: 'Togo', code: 'TG' },
    { displayLabel: 'Tonga', code: 'TO' },
    { displayLabel: 'Trinidad and Tobago', code: 'TT' },
    { displayLabel: 'Tunisia', code: 'TN' },
    { displayLabel: 'Turkey', code: 'TR' },
    { displayLabel: 'Turkmenistan', code: 'TM' },
    { displayLabel: 'Tuvalu', code: 'TV' },
    { displayLabel: 'Uganda', code: 'UG' },
    { displayLabel: 'Ukraine', code: 'UA' },
    { displayLabel: 'United Arab Emirates', code: 'AE' },
    { displayLabel: 'United Kingdom', code: 'GB' },
    { displayLabel: 'United States', code: 'US' },
    { displayLabel: 'Uruguay', code: 'UY' },
    { displayLabel: 'Uzbekistan', code: 'UZ' },
    { displayLabel: 'Vanuatu', code: 'VU' },
    { displayLabel: 'Venezuela', code: 'VE' },
    { displayLabel: 'Vietnam', code: 'VN' },
    { displayLabel: 'Yemen', code: 'YE' },
    { displayLabel: 'Zambia', code: 'ZM' },
    { displayLabel: 'Zimbabwe', code: 'ZW' }
  ];
